{
 "title": "GT7",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"car_speed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Boost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"boost\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cgear\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Position",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_positions\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_position\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"gt7\" and\r\n    r._field == \"rpm\"\r\n  )"
    }
   ]
  },
  {
   "title": "Times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"last_lap\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n  |> distinct(column: \"_value\")\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"best_lap\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n  |> distinct(column: \"_value\")\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_lap\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n  |> distinct(column: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Throttle/Break",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"throttle\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"breaking_force\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n"
    }
   ]
  },
  {
   "title": "Fuel Capacity/Remaining",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel_capacity\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fuel_remaining\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Tire Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_speed_FL\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_speed_FR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_speed_RL\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_speed_RR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Tire Slip Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_slip_ratio_FL\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_slip_ratio_FR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_slip_ratio_RL\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_slip_ratio_RR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Tire Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_temp_FL\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_temp_FR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_temp_RL\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tire_temp_RR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Suspention",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"suspension_FL\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"suspension_FR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"suspension_RL\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"suspension_RR\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Ride Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"initbucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gt7\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ride_height\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n"
    }
   ]
  }
 ]
}